src/objects/cfp_Data_Movements__c.object
<CustomObject>
    <fields>
        <fullName>cfp_FunctionalProcess__c</fullName>
        <label>Functional Prcess</label>
        <referenceTo>cfp_FunctionalProcess__c</referenceTo>
        <relationshipName>cfp_functionalsteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>cfp_is_API_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is API Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cfp_movementtype__c</fullName>
        <label>Movement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cfp_order__c</fullName>
        <label>order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Data Movement</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cfp_FunctionalProcess__c.object
<CustomObject>
    <fields>
        <fullName>cfp_Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Functional Process</label>
    <nameField>
        <label>cfp_FunctionalProcess Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cfp_getDataMovements.cls
/**
 * Created by dkrizanovic on 22/10/2024.
 */

public with sharing class cfp_getDataMovements {

    @AuraEnabled
    public static List<cfp_Data_Movements__c> getSteps(Id fpId) {
        List<cfp_Data_Movements__c> allSteps = [SELECT Name, cfp_order__c, cfp_movementtype__c, cfp_is_API_Call__c, cfp_FunctionalProcess__r.Name FROM cfp_Data_Movements__c WHERE cfp_FunctionalProcess__c = :fpId ORDER BY cfp_order__c ASC];


        return allSteps;
    }
}